### ISSUE TITLE
Can't compile as 'AsyncElegantOTA' is archived and 'esp_int_wdt.h' is now private

### ISSUE THREAD

**Issue by berrydejager** [ednieuw/Lilygo-WristWatch#1]
While compiling, using Debian 12, your V13 project for the v3 watch, I stumbled upon the following error:

```
In file included from ~/Lilygo-T-Watch-2020/Liygo-WristWatchESP32-V013/Liygo-WristWatchESP32-V013.ino:98:
~/Arduino/libraries/AsyncElegantOTA/src/AsyncElegantOTA.h:18:14: fatal error: esp_int_wdt.h: No such file or directory
   18 |     #include "esp_int_wdt.h"
      |              ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1
```

As far as I can find out the `esp_int_wdt.h` file is now private and the [AsyncElegantOTA project is in archived state](https://github.com/ayushsharma82/AsyncElegantOTA).

Do you experience the same behaviour now?

**Comment by berrydejager** [comment]
My bad... as I selected the v3.01 as board version, reverting to v2.0.14 made it compile! Thanks!

**Comment by ednieuw** [comment]
Here is a solution for ElegantOTA on V3.0.1
https://github.com/esphome/ESPAsyncWebServer/issues/32
